### ISSUE TITLE
Stopped working - Unable to initialize authentication methods

### ISSUE THREAD

**Issue by ChaosCoder** [mattrajca/sudo-touchid#11]
I had successfully sudo-touchid running in `/usr/local/bin/` and today it stopped working. I removed it, cloned the repo again, built it again but with no success, the error message keeps being the same:
```
% ./sudo whoami
Sorry, try again.
sudo: Unable to initialize authentication methods.
```

This is the result when I type `ls -la` (but again, it worked without touching it before):
```
-rwsr-xr-x  1 root  wheel  450768  2 Jan 21:13 sudo
```

Anyone got a clue what happened? Already restarted my Mac, didn't help.

**Comment by ChaosCoder** [comment]
Turns out, my Touch ID was reset (I saw my touch bar going off and not coming back until I restarted), so my only fingerprint was removed. This broke sudo-touchid of course. Reading my finger to Touch ID resolved the issue.

**Comment by simplenotezy** [comment]
I have this error. I have reset my fingerprints. Still have the issue.

**Comment by simplenotezy** [comment]
Related to https://github.com/mattrajca/sudo-touchid/issues/22
