### ISSUE TITLE
Why fork instead of PAM module?

### ISSUE THREAD

**Issue by lm2s** [mattrajca/sudo-touchid#2]
macOS, as many other *nix systems, has PAM. Is there a specific reason to not create a PAM module that would interface with `sudo` instead of the fork?

EDIT: PAM was first introduced in Linux not Unix, changed the wording.

**Comment by rejsmont** [comment]
+1

**Comment by WANG-lp** [comment]
+1

**Comment by mattrajca** [comment]
Someone else has already implemented Touch ID support as a PAM module: https://github.com/hamzasood/pam_touchid

I'll still keep `sudo-touchid` around.
