### ISSUE TITLE
A simpler method for using Touch ID with `sudo`

### ISSUE THREAD

**Issue by raylas** [mattrajca/sudo-touchid#27]
On Touch ID enabled MacBook Pros add the following line **to the top** of `/etc/pam.d/sudo`:

`auth sufficient pam_tid.so`

Not sure how new/recent this is capability is, but I thought it might be of interest to this repo.

**Comment by serverwentdown** [comment]
wow gonna switch to this tonight.

**Comment by serverwentdown** [comment]
wow yes it does the trick! amazing.

**Comment by tomlobato** [comment]
amazing! 

the next level is to have remote ssh touch id support :)
ssh me@mysrv
me@mysrv $ sudo bash <-- touch
root@mysrv #

**Comment by tomlobato** [comment]
amazing!

the next level is to have remote ssh touch id support :)
ssh me@mysrv
me@mysrv $ sudo su <-- touch
root@mysrv #

**Comment by noomorph** [comment]
It is a clear winner method. Kudos to @raylas  !

**Comment by raylas** [comment]
Glad to shed some light on it. I've used **sudo-touchid** for a while now and I'm still thankful for the work this repo has done!

Now to tackle Touch ID for ssh private key auth like @tomlobato mentioned...

**Comment by raylas** [comment]
@tomlobato found this repo/agent that allows you to use Touch ID and a key stored in the secure enclave to authenticate to SSH servers:

[https://github.com/ntrippar/sekey](https://github.com/ntrippar/sekey)

**Comment by tomlobato** [comment]
Awesome. Tks @raylas!

**Comment by hu13** [comment]
is there a way to make it work for `su`?

`auth sufficient pam_tid.so` doesn't.
