### ISSUE TITLE
Will this work with a third-party fingerprint reader?

### ISSUE THREAD

**Issue by JunielKatarn** [mattrajca/sudo-touchid#4]
For pre-2016 MacBook Pro models, provided the laptop recognizes the biometric reader, can this sudo variant use such hardware?

**Comment by mattrajca** [comment]
`sudo-touchid` currently uses Apple's LocalAuthentication framework which only works with Touch ID. I'm not aware of any other biometric APIs on macOS that would allow us to access third-party hardware.
