### ISSUE TITLE
Not working in 10.12.1

### ISSUE THREAD

**Issue by j-mcnally** [mattrajca/sudo-touchid#5]
Hey there. I have a later 2016 mac book pro.

Love the project but I just get a password prompt when I run sudo.

Wanted to make sure I am not doing something wrong.

I know you said it might not work in 10.12.

Anything I can do to help?

**Comment by j-mcnally** [comment]
Ohhhh hmmm. the code i cloned looks like it didnt have biometrics enabled.

Odd.

**Comment by j-mcnally** [comment]
hmm i fixed and recompiled but now im not getting any prompts.

**Comment by j-mcnally** [comment]
More updates. I am seeing 

```
LAClient: __52-[LAClient evaluatePolicy:options:uiDelegate:reply:]_block_invoke -> (null), Error Domain=com.apple.LocalAuthentication Code=-7 "No fingers are enrolled with Touch ID." UserInfo={NSLocalizedDescription=No fingers are enrolled with Touch ID.} on <LAClient: 0x7ff302000180>
```

but i have 3 fingers

**Comment by j-mcnally** [comment]
I think the issue is its looking for root's fingers....

**Comment by j-mcnally** [comment]
yep that was exactly it. i enabled the root user and added a finger print and it works. any way to make this use the local user's finger print?

**Comment by evanmhm** [comment]
How exactly did you do that? I am in the same position of not being any prompts.

**Comment by mattrajca** [comment]
Hi @j-mcnally,

I currently don't have a MacBook with Touch ID on hand. What happens if you pass: `0x3f0` for the policy in `evaluatePolicy:`? It should use the current user's fingerprints instead of root's.

**Comment by mattrajca** [comment]
This should be fixed in ToT.

**Comment by j-mcnally** [comment]
Sorry for not getting back to you. Will try thanks.
