### ISSUE TITLE
Only requires Touch ID once

### ISSUE THREAD

**Issue by evanmhm** [mattrajca/sudo-touchid#7]
I am on a MBP 2016 on 10.12.1 and using j-mcnally's method of enabling root user and adding a fingerprint, I was able to get it to work, but only once. Once it authenticated with my finger print, sudo no longer required authentication in other sessions of terminal, after relaunching terminal, or after logging in or out. After rebooting, the entire thing stops working and just asks for password inline.

**Comment by evanmhm** [comment]
I deleted the custom sudo from `usr/local/bin`, rebuilt the project, and now `./sudo -s` in the build directory doesn't require a password of any type.

**Comment by mattrajca** [comment]
I believe `sudo` remembers your password for a short grace period which is why it may appear it doesn't require a password at times.

**Comment by mattrajca** [comment]
If the whole thing stops working after rebooting, it's probably because your `PATH` is not being persisted across reboots and the system's build of `sudo` gets used again.
