### ISSUE TITLE
Update to sudo-83

### ISSUE THREAD

**Issue by hjelmn** [mattrajca/sudo-touchid#8]
Apple has made the 10.12 source available but it isn't correctly linked from the main page. See https://opensource.apple.com/release/os-x-1012.html

Would probably be a good idea to update from the sudo-77 base.

**Comment by Cee** [comment]
Hey, I've forked this project and merged sudo to sudo-83.
Take a look :) https://github.com/Cee/sudo-touchid/tree/sudo-83

(Not fully tested, but worked on my MacBook Pro 15' with Touch Bar)
